### ISSUE TITLE
add feature to deploy models to DeepImageJ

### ISSUE THREAD

**Issue by cmohl2013** [yapic/yapic#14]
DeepImageJ is an ImageJ plugin that applies tensorflow models in tile-wise fashion to imageJ images.

Currently, only 2d models are supported. 

YAPiC needs a feature to export keras model (unet_2d) to tensorflow saved model, including metadata (xml file and example image) to a DeepImageJ bundled model.

**Comment by PoulomiA** [comment]
WIll the multi_z models be supported in the future?
