### ISSUE TITLE
Strange results images

### ISSUE THREAD

**Issue by aryehw** [yapic/yapic#58]
I ran the leaves examples for 20 epochs using --cpu (since my GPU has only 4GB RAM), and it got through the 20 epochs overnight. 
I then used the yapic predict command to test the model. 
I did not expect that the segmentation would be accurate, but I wanted to check the rest of the mechanics of running yapic.
The strange thing is that the images in the results directory came up in Fiji as a stack of 720 lines x 6. (The test images are 790x790).

To get a 790x790 x6 channel image, I needed to do Image>Stack>Reslice... and flip 90 degrees from left.   
The metadata shows that when the image is loaded, it appears as::
Channels = 1
Time frames  = 790
SizeX = 6
SizeY = 790
SizeZ = 1

**Comment by cmohl2013** [comment]
Dear @aryehw thank you for reporting this important issue. I am on holiday and can not test anything. If you would like to try something out I recommend to install following yapic and yapic_io versions:

```
pip install yapic_io==0.1.2
pip install yapic==1.2.3
```` 

Those were the last versions I released and I also used them myself for classification projects. I guess the prediction will produce image with correct dimensions.

**Comment by aryehw** [comment]
Thank you for your response.
This produces the expected output, with the correct dimensions (x,y, 6 channels in a hyperstack).

**Comment by aryehw** [comment]
More strangeness.
I am now running yapic on a GPU cluster, and it runs very nicely - 50x faster than on my cpu.
So I am trying it with labeled images instead of the ilp file, and that also works fine.

Except that I chose to annotate the leaves image with only 4 classes + background, so I expect the predict output to be a total of 5 channels (background and 4 leaf types). However, I get 6 channels total, even though my labels only run 0-4.

Why would that happen?

**Comment by aryehw** [comment]
Further on this issue -- I am training and then predicting on a set of plant images. The label images have three classes - 0 = background, 1 = pods, 2 = stems. The training goes fine. When I run yapic predict, i get the results, and these images have two classes only. That is, the pods get predicted pretty well, but the stems and background are combined into one channel, so the prediction images are only two channels. Is this the expected behavior?

I attached an example label image. 
[SR7.201.4 GLENN IMAGE 4_cropped_labels.tif.zip](https://github.com/yapic/yapic/files/9262285/SR7.201.4.GLENN.IMAGE.4_cropped_labels.tif.zip)

**Comment by cmohl2013** [comment]
@aryehw 
Apologies for the delayed comment.

Yes, training of only two channels is expected with this label file.

YAPiC supports sparse labelling, i.e. you do not have to label the complete image. Pixels in the label image with value 0 are interpreted as no label. To add a background label class, you should add additional labels with value 3.

To quickly fix your label images, you could use `Process>>Math>Add...` function in Fiji and add 1 to your label values.

**Comment by aryehw** [comment]
Thank you for your response.

**Comment by aryehw** [comment]
I added 1 to each of the label images, and retrained the model. That worked fine.
However, when I tried to do the prediction, I ended with the following error:
IndexError: index 2 is out of bounds for axis 1 with size 2

Can you tell me what happened?

Update: I erased the old prediction results from the  results directory, and then ran it again. Now it appears to work with  out that error.
